### ISSUE TITLE
Error Starting gogeta

### ISSUE THREAD

**Issue by Gouthamve** [arkenio/gogeta#11]
Hi, I am getting an error when trying to run gogeta.
I ran the etcd image in a container and then ran the following commands

```bash
core@core ~/gogeta $ etcdctl mkdir /domains
core@core ~/gogeta $ etcdctl mkdir /services
core@core ~/gogeta $ etcdctl mkdir /domains/test.com
core@core ~/gogeta $ etcdctl set /domains/test.com/type uri
core@core ~/gogeta $ etcdctl set /domains/test.com/value 172.17.0.29:80
```
my etcd image was running on 172.17.0.48:4001

So used the following command:

```bash
root@8f732eed0887:/usr/local/go/src/github.com/arkenio/gogeta# gogeta -etcdAddress="http://172.17.0.48:4001" \
>            -domainDir="/domains" \
>            -serviceDir="/services" \
>            -templateDir="/usr/local/go/src/github.com/nuxeo/gogeta/templates"
```
This is the error and it repeats again and again.
```go
E0610 10:30:13.230260      26 etcdwatcher.go:54] Error when watching /domains : 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/domains?recursive=true&wait=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0610 10:30:13.231045      26 etcdwatcher.go:55] Waiting 1 second and relaunch watch
E0610 10:30:13.231924      26 etcdwatcher.go:54] Error when watching /services : 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/services?recursive=true&wait=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0610 10:30:13.232254      26 etcdwatcher.go:55] Waiting 1 second and relaunch watch
```

I am a complete beginner here so I have no idea where I am wrong, but gogeta is the exact thing that I want.
Thanks for the awesome project.

**Comment by dmetzler** [comment]
Hello, it seems that your pointing to the IP address of the container to reach etcd. etcd runs on the docker host (the CoreOS host) and thus you should point to the bridge interface of the container (172.17.42.1 or something like that) which connect to the host.

To test the reachability of etcd you should issue a curl command from the container on the address you're using like :

         curl -L http://172.17.42.1:4001/v2/keys/domains

**Comment by Gouthamve** [comment]
That works! Thanks.
